name: Feature request
description: Create a Feature request
title: '[Feature request] '
labels:
  - 'Feature-request'
body:
  - type: markdown
    attributes:
      value: |
        Describe the Feature request in a single sentence
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the feature request in more detail
      placeholder: |
        As a [type of user], I want [some goal] so that [some reason].
    validations:
        required: true
  - type: markdown
    attributes:
      value: |
        ## Acceptance criteria
        List the criteria that must be met for this feature request to be considered complete
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance criteria
      description: List the criteria that must be met for this feature request to be considered complete
      placeholder: |
        - [ ] Criteria 1
        - [ ] Criteria 2
        - [ ] Criteria 3
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Sub Feature requests
        List the feature requests that need to be completed to achieve the acceptance criteria
  - type: textarea
    id: feature-requests
    attributes:
      label: Feature requests
      description: List the feature requests that need to be completed to achieve the acceptance criteria
      placeholder: |
        - [ ] Feature request 1
        - [ ] Feature request 2
        - [ ] Feature request 3
    validations:
      required: true