name: Task
description: Create a Task
title: '[Task] '
projects:
  - 'murunu/4'
labels:
  - 'Task'
body:
  - type: markdown
    attributes:
      value: |
        Describe the Task in a single sentence
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the task in more detail
      placeholder: |
        As a [type of user], I want [some goal] so that [some reason].
    validations:
        required: true
  - type: markdown
    attributes:
      value: |
        ## Acceptance criteria
        List the criteria that must be met for this task to be considered complete
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance criteria
      description: List the criteria that must be met for this task to be considered complete
      placeholder: |
        - [ ] Criteria 1
        - [ ] Criteria 2
        - [ ] Criteria 3
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Sub Tasks
        List the tasks that need to be completed to achieve the acceptance criteria
  - type: textarea
    id: tasks
    attributes:
      label: Tasks
      description: List the tasks that need to be completed to achieve the acceptance criteria
      placeholder: |
        - [ ] Task 1
        - [ ] Task 2
        - [ ] Task 3
    validations:
      required: true