name: User story
description: Create a user story
title: '[User story] '
labels:
  - 'User-story'
body:
  - type: markdown
    attributes:
      value: |
        Describe the user story in a single sentence
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the user story in more detail
      placeholder: |
        As a [type of user], I want [some goal] so that [some reason].
    validations:
        required: true
  - type: markdown
    attributes:
      value: |
        ## Acceptance criteria
        List the criteria that must be met for this user story to be considered complete
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance criteria
      description: List the criteria that must be met for this user story to be considered complete
      placeholder: |
        - [ ] Criteria 1
        - [ ] Criteria 2
        - [ ] Criteria 3
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Tasks
        List the tasks that need to be completed to achieve the acceptance criteria
  - type: textarea
    id: tasks
    attributes:
      label: Tasks
      description: List the tasks that need to be completed to achieve the acceptance criteria
      placeholder: |
        - [ ] Task 1
        - [ ] Task 2
        - [ ] Task 3
    validations:
      required: true